"""
Verified MIT faculty names scraped from official MIT department directories.
This serves as the ground-truth whitelist for filtering OpenAlex results.

Sources (all fetched April 2026):
- biology.mit.edu/faculty-and-research/faculty/
- chemistry.mit.edu/faculty/
- physics.mit.edu/faculty/
- math.mit.edu/directory/faculty/
- eecs.mit.edu/role/faculty/
- eaps.mit.edu/people/
- economics.mit.edu/people/faculty
- be.mit.edu/directory (Biological Engineering)
- cheme.mit.edu/people/faculty/ (Chemical Engineering)
- meche.mit.edu/people (Mechanical Engineering)
- cee.mit.edu/people/faculty/ (Civil & Environmental)
- dmse.mit.edu/people/faculty (Materials Science)
- bcs.mit.edu/faculty (Brain & Cognitive Sciences)
- aeroastro.mit.edu (AeroAstro - partial)
- nse.mit.edu (Nuclear Science & Engineering, via WP API)
- mcgovern.mit.edu/researchers/
- ki.mit.edu/people/faculty (Koch Institute)
- lids.mit.edu/people
- idss.mit.edu/people/
"""

# Each entry: (name, [departments])
# Names are as listed on the official directory pages.

VERIFIED_FACULTY = {
    # ── Biology (Course 7) ──
    "Tania A. Baker": ["Biology"],
    "David Bartel": ["Biology"],
    "Facundo Batista": ["Biology"],
    "Stephen Bell": ["Biology", "Koch Institute"],
    "Laurie A. Boyer": ["Biology", "BioE", "Koch Institute"],
    "Christopher Burge": ["Biology", "Koch Institute"],
    "Eliezer Calo": ["Biology", "Koch Institute"],
    "Lindsay Case": ["Biology", "Koch Institute"],
    "Iain M. Cheeseman": ["Biology"],
    "Yiyin Erin Chen": ["Biology"],
    "Jianzhu Chen": ["Biology", "Koch Institute"],
    "Sallie W. Chisholm": ["Biology", "CEE"],
    "Penny Chisholm": ["Biology", "CEE"],
    "Olivia Corradin": ["Biology"],
    "Joseph Davis": ["Biology"],
    "Joey Davis": ["Biology"],
    "Catherine Drennan": ["Biology", "Chemistry"],
    "Catherine L. Drennan": ["Biology", "Chemistry"],
    "Mary Gehring": ["Biology", "BioE"],
    "Alan D. Grossman": ["Biology"],
    "Leonard P. Guarente": ["Biology", "Koch Institute"],
    "Michael T. Hemann": ["Biology", "Koch Institute"],
    "Whitney Henry": ["Biology", "Koch Institute"],
    "H. Robert Horvitz": ["Biology", "Koch Institute", "McGovern"],
    "David Housman": ["Biology", "Koch Institute"],
    "Siniša Hrvatin": ["Biology"],
    "Yunha Hwang": ["Biology", "EECS"],
    "Barbara Imperiali": ["Biology", "Chemistry"],
    "Tyler Jacks": ["Biology", "Koch Institute"],
    "Rudolf Jaenisch": ["Biology", "Koch Institute"],
    "Ankur Jain": ["Biology"],
    "Matthew G. Jones": ["Biology", "Koch Institute"],
    "Matt Jones": ["Biology", "Koch Institute"],
    "Chris A. Kaiser": ["Biology"],
    "Amy E. Keating": ["Biology", "BioE", "Koch Institute"],
    "Kristin Knouse": ["Biology", "Koch Institute"],
    "Sally Kornbluth": ["Biology"],
    "Monty Krieger": ["Biology"],
    "Rebecca Lamason": ["Biology"],
    "Eric S. Lander": ["Biology", "Koch Institute"],
    "Michael T. Laub": ["Biology"],
    "Douglas Lauffenburger": ["Biology", "BioE", "Koch Institute"],
    "Jacqueline Lees": ["Biology", "Koch Institute"],
    "Ruth Lehmann": ["Biology"],
    "Daniel Lew": ["Biology", "Koch Institute"],
    "Pulin Li": ["Biology"],
    "Gene-Wei Li": ["Biology"],
    "Troy Littleton": ["Biology", "BCS"],
    "Harvey F. Lodish": ["Biology", "BioE"],
    "Sebastian Lourido": ["Biology"],
    "Adam C. Martin": ["Biology"],
    "Hernandez Moura Silva": ["Biology"],
    "Elly Nedivi": ["Biology", "BCS"],
    "Sergey Ovchinnikov": ["Biology"],
    "David C. Page": ["Biology", "Koch Institute"],
    "Sara Prescott": ["Biology", "BCS"],
    "Peter Reddien": ["Biology"],
    "Alison E. Ringel": ["Biology", "Koch Institute"],
    "Francisco J. Sánchez-Rivera": ["Biology", "Koch Institute"],
    "Thomas U. Schwartz": ["Biology"],
    "Yadira Soto-Feliciano": ["Biology", "Koch Institute"],
    "Stefani Spranger": ["Biology", "Koch Institute"],
    "Zuri Sullivan": ["Biology"],
    "Susumu Tonegawa": ["Biology", "BCS"],
    "Ron Vale": ["Biology"],
    "Matthew Vander Heiden": ["Biology", "Koch Institute"],
    "Seychelle M. Vos": ["Biology", "Koch Institute"],
    "Graham C. Walker": ["Biology", "Koch Institute"],
    "Bruce Walker": ["Biology"],
    "Robert A. Weinberg": ["Biology", "Koch Institute"],
    "Brandon Weissbourd": ["Biology", "BCS"],
    "Jonathan Weissman": ["Biology", "Koch Institute"],
    "Matthew A. Wilson": ["Biology", "BCS"],
    "Harikesh S. Wong": ["Biology"],
    "Michael B. Yaffe": ["Biology", "BioE", "Koch Institute"],
    "Yukiko Yamashita": ["Biology"],
    "Omer H. Yilmaz": ["Biology", "Koch Institute"],
    "Richard A. Young": ["Biology", "Koch Institute"],

    # ── Chemistry (Course 5) ──
    "Moungi Bawendi": ["Chemistry"],
    "Stephen Leffler Buchwald": ["Chemistry"],
    "Stephen Buchwald": ["Chemistry"],
    "Jianshu Cao": ["Chemistry"],
    "Sylvia Teresse Ceyer": ["Chemistry"],
    "Sylvia Ceyer": ["Chemistry"],
    "Arup K. Chakraborty": ["Chemistry", "Physics"],
    "Arup Chakraborty": ["Chemistry", "Physics"],
    "Christopher C. Cummins": ["Chemistry"],
    "Rick Lane Danheiser": ["Chemistry"],
    "Rick Danheiser": ["Chemistry"],
    "John M. Deutch": ["Chemistry"],
    "Masha Elkin": ["Chemistry"],
    "John M. Essigmann": ["Chemistry", "BioE"],
    "Robert W. Field": ["Chemistry"],
    "Danna Freedman": ["Chemistry"],
    "Robert J. Gilliard, Jr.": ["Chemistry"],
    "Robert Guy Griffin": ["Chemistry"],
    "Mei Hong": ["Chemistry"],
    "Timothy F. Jamison": ["Chemistry"],
    "Jeremiah A. Johnson": ["Chemistry", "Koch Institute"],
    "Oleta Johnson": ["Chemistry"],
    "Laura L Kiessling": ["Chemistry", "Koch Institute"],
    "Laura Kiessling": ["Chemistry", "Koch Institute"],
    "Alexander M. Klibanov": ["Chemistry", "BioE"],
    "Heather J. Kulik": ["Chemistry"],
    "Stephen J. Lippard": ["Chemistry"],
    "Brett McGuire": ["Chemistry"],
    "Mohammad Movassaghi": ["Chemistry"],
    "Keith Adam Nelson": ["Chemistry"],
    "Keith Nelson": ["Chemistry"],
    "Elizabeth Marie Nolan": ["Chemistry"],
    "Elizabeth Nolan": ["Chemistry"],
    "Sam Peng": ["Chemistry"],
    "Bradley L. Pentelute": ["Chemistry", "Koch Institute"],
    "Alexander T. Radosevich": ["Chemistry"],
    "Ronald T. Raines": ["Chemistry", "Koch Institute"],
    "Ron Raines": ["Chemistry", "Koch Institute"],
    "Yuriy Román": ["Chemistry"],
    "Gabriela S. Schlau-Cohen": ["Chemistry"],
    "Richard Royce Schrock": ["Chemistry"],
    "Alex K. Shalek": ["Chemistry", "Koch Institute"],
    "Yang Shao-Horn": ["Chemistry", "MechE"],
    "Matthew D. Shoulders": ["Chemistry"],
    "Susan Solomon": ["Chemistry", "EAPS"],
    "Jeffrey I. Steinfeld": ["Chemistry"],
    "JoAnne Stubbe": ["Chemistry"],
    "Daniel L.M. Suess": ["Chemistry"],
    "Yogesh Surendranath": ["Chemistry"],
    "Timothy Manning Swager": ["Chemistry"],
    "Timothy Swager": ["Chemistry"],
    "Steven R. Tannenbaum": ["Chemistry", "BioE"],
    "Troy Van Voorhis": ["Chemistry"],
    "Xiao Wang": ["Chemistry"],
    "Alison Wendlandt": ["Chemistry"],
    "Adam P. Willard": ["Chemistry"],
    "Bin Zhang": ["Chemistry"],

    # ── Physics (Course 8) ──
    "Raymond Ashoori": ["Physics"],
    "John Belcher": ["Physics"],
    "George Benedek": ["Physics"],
    "Edmund Bertschinger": ["Physics"],
    "Kevin Burdge": ["Physics"],
    "Claude Canizares": ["Physics"],
    "Paola Cappellaro": ["Physics", "NSE"],
    "Deepto Chakrabarty": ["Physics"],
    "Joseph Checkelsky": ["Physics"],
    "Min Chen": ["Physics"],
    "Soonwon Choi": ["Physics"],
    "Isaac Chuang": ["Physics", "EECS"],
    "Riccardo Comin": ["Physics"],
    "Janet Conrad": ["Physics"],
    "William Detmold": ["Physics"],
    "Anna-Christina Eilers": ["Physics"],
    "Netta Engelhardt": ["Physics"],
    "Matthew Evans": ["Physics"],
    "Nikta Fakhri": ["Physics"],
    "Peter Fisher": ["Physics"],
    "Richard Fletcher": ["Physics"],
    "Joseph Formaggio": ["Physics"],
    "Anna Frebel": ["Physics"],
    "Liang Fu": ["Physics"],
    "Ronald Fernando Garcia Ruiz": ["Physics"],
    "Nuh Gedik": ["Physics"],
    "Jeff Gore": ["Physics"],
    "Ore Gottlieb": ["Physics"],
    "Alan Guth": ["Physics"],
    "Daniel Harlow": ["Physics"],
    "Philip Harris": ["Physics"],
    "Aram Harrow": ["Physics"],
    "Or Hen": ["Physics"],
    "Jacqueline Hewitt": ["Physics"],
    "Scott Hughes": ["Physics"],
    "Gian Michele Innocenti": ["Physics"],
    "Mikhail Ivanov": ["Physics"],
    "Robert Jaffe": ["Physics"],
    "Pablo Jarillo-Herrero": ["Physics"],
    "Zhurun Judy Ji": ["Physics"],
    "Steven Johnson": ["Physics", "Math"],
    "Long Ju": ["Physics"],
    "David Kaiser": ["Physics"],
    "Erin Kara": ["Physics"],
    "Mehran Kardar": ["Physics"],
    "Marc Kastner": ["Physics"],
    "Wolfgang Ketterle": ["Physics"],
    "Patrick Lee": ["Physics"],
    "Yen-Jie Lee": ["Physics"],
    "Leonid Levitov": ["Physics"],
    "Hong Liu": ["Physics"],
    "Kiyoshi Masui": ["Physics"],
    "Nergis Mavalvala": ["Physics"],
    "Michael McDonald": ["Physics"],
    "Max Metlitski": ["Physics"],
    "Sarah Millholland": ["Physics"],
    "Leonid Mirny": ["Physics"],
    "Lina Necib": ["Physics"],
    "William Oliver": ["Physics", "EECS"],
    "Christoph Paus": ["Physics"],
    "Krishna Rajagopal": ["Physics"],
    "Brooke Russell": ["Physics"],
    "Sara Seager": ["Physics", "EAPS"],
    "Phiala Shanahan": ["Physics"],
    "Shu-Heng Shao": ["Physics"],
    "Robert Simcoe": ["Physics"],
    "Tracy Slatyer": ["Physics"],
    "Eluned Smith": ["Physics"],
    "Marin Soljačić": ["Physics"],
    "Iain Stewart": ["Physics"],
    "Julien Tailleur": ["Physics"],
    "Washington Taylor": ["Physics"],
    "Max Tegmark": ["Physics"],
    "Jesse Thaler": ["Physics", "IDSS"],
    "Senthil Todadri": ["Physics"],
    "Salvatore Vitale": ["Physics"],
    "Mark Vogelsberger": ["Physics"],
    "Vladan Vuletić": ["Physics"],
    "Xiao-Gang Wen": ["Physics"],
    "Frank Wilczek": ["Physics"],
    "Michael Williams": ["Physics", "IDSS"],
    "Lindley Winslow": ["Physics"],
    "Barton Zwiebach": ["Physics"],
    "Martin Zwierlein": ["Physics"],

    # ── Math (Course 18) ──
    "Michael Artin": ["Math"],
    "Shaoyun Bai": ["Math"],
    "John Baldwin": ["Math"],
    "Martin Bazant": ["Math"],
    "Bonnie Berger": ["Math"],
    "Olivier Bernardi": ["Math"],
    "Roman Bezrukavnikov": ["Math"],
    "Jacopo Borga": ["Math"],
    "Alexei Borodin": ["Math"],
    "John Bush": ["Math"],
    "Henry Cohn": ["Math"],
    "Tobias Holck Colding": ["Math"],
    "Laurent Demanet": ["Math", "EAPS"],
    "Semyon Dyatlov": ["Math"],
    "Alan Edelman": ["Math"],
    "Pavel Etingof": ["Math"],
    "Michel Goemans": ["Math"],
    "Shafi Goldwasser": ["Math", "EECS"],
    "Larry Guth": ["Math"],
    "Jeremy Hahn": ["Math"],
    "Anette Hosoi": ["Math", "MechE"],
    "David Jerison": ["Math"],
    "Victor Kac": ["Math"],
    "Christoph Kehle": ["Math"],
    "Jonathan Kelner": ["Math"],
    "Tom Leighton": ["Math"],
    "Aleksandr Logunov": ["Math"],
    "George Lusztig": ["Math"],
    "Davesh Maulik": ["Math"],
    "Richard Melrose": ["Math"],
    "Haynes Miller": ["Math"],
    "William Minicozzi": ["Math"],
    "Dor Minzer": ["Math"],
    "Ankur Moitra": ["Math", "EECS"],
    "Elchanan Mossel": ["Math", "IDSS"],
    "Tomasz Mrowka": ["Math"],
    "Pablo Parrilo": ["Math", "LIDS", "IDSS"],
    "Bjorn Poonen": ["Math"],
    "Alexander Postnikov": ["Math"],
    "Philippe Rigollet": ["Math", "LIDS", "IDSS"],
    "Rodolfo Rosales": ["Math"],
    "Paul Seidel": ["Math"],
    "Scott Sheffield": ["Math"],
    "Peter Shor": ["Math"],
    "Michael Sipser": ["Math"],
    "Gigliola Staffilani": ["Math"],
    "Richard Stanley": ["Math"],
    "Gilbert Strang": ["Math"],
    "Nike Sun": ["Math"],
    "Andrew Sutherland": ["Math"],
    "Naomi Sweeting": ["Math"],
    "David Vogan": ["Math"],
    "Martin Wainwright": ["Math", "LIDS", "IDSS"],
    "Zhiwei Yun": ["Math"],
    "Wei Zhang": ["Math"],
    "Yufei Zhao": ["Math"],

    # ── EECS (Course 6) ──
    "Hal Abelson": ["EECS"],
    "Elfar Adalsteinsson": ["EECS"],
    "Fadel Adib": ["EECS"],
    "Anant Agarwal": ["EECS"],
    "Pulkit Agrawal": ["EECS", "LIDS"],
    "Akintunde Akinwande": ["EECS"],
    "Mohammad Alizadeh": ["EECS"],
    "Saman Amarasinghe": ["EECS"],
    "Jacob Andreas": ["EECS"],
    "Regina Barzilay": ["EECS", "Koch Institute"],
    "Stephen Bates": ["EECS", "LIDS"],
    "Sara Beery": ["EECS"],
    "Adam Belay": ["EECS"],
    "Karl Berggren": ["EECS"],
    "Dimitri Bertsekas": ["EECS", "LIDS", "IDSS"],
    "Robert Berwick": ["EECS", "LIDS"],
    "Sangeeta Bhatia": ["EECS", "Koch Institute"],
    "Abigail Bodner": ["EECS", "LIDS", "EAPS"],
    "Duane Boning": ["EECS"],
    "Guy Bresler": ["EECS", "LIDS"],
    "Tamara Broderick": ["EECS", "LIDS"],
    "Vladimir Bulović": ["EECS"],
    "Michael Carbin": ["EECS"],
    "Anantha Chandrakasan": ["EECS", "LIDS"],
    "Suraj Cheema": ["EECS", "DMSE"],
    "Adam Chlipala": ["EECS"],
    "Connor Wilson Coley": ["EECS"],
    "Connor Coley": ["EECS"],
    "Henry Corrigan-Gibbs": ["EECS"],
    "Munther Dahleh": ["EECS", "IDSS"],
    "Luca Daniel": ["EECS"],
    "Constantinos Daskalakis": ["EECS", "LIDS"],
    "Costis Daskalakis": ["EECS", "LIDS"],
    "Randall Davis": ["EECS"],
    "Christina Delimitrou": ["EECS"],
    "Erik Demaine": ["EECS"],
    "Srini Devadas": ["EECS"],
    "Priya Donti": ["EECS", "LIDS"],
    "Frederic Durand": ["EECS"],
    "Dirk Englund": ["EECS"],
    "Gabriele Farina": ["EECS", "LIDS"],
    "William Freeman": ["EECS"],
    "Mohsen Ghaffari": ["EECS"],
    "Marzyeh Ghassemi": ["EECS", "LIDS"],
    "Manya Ghobadi": ["EECS"],
    "David Gifford": ["EECS", "BioE"],
    "Shafrira Goldwasser": ["EECS"],
    "Polina Golland": ["EECS", "IDSS"],
    "John Guttag": ["EECS"],
    "Dylan Hadfield-Menell": ["EECS"],
    "Song Han": ["EECS"],
    "Kaiming He": ["EECS"],
    "Sam Hopkins": ["EECS"],
    "Phillip Isola": ["EECS"],
    "Tommi Jaakkola": ["EECS", "IDSS"],
    "Daniel Jackson": ["EECS"],
    "Stefanie Jegelka": ["EECS", "IDSS"],
    "M. Frans Kaashoek": ["EECS"],
    "Leslie Kaelbling": ["EECS"],
    "Yael Kalai": ["EECS"],
    "David Karger": ["EECS"],
    "Dina Katabi": ["EECS"],
    "Manolis Kellis": ["EECS"],
    "Yoon Kim": ["EECS"],
    "Tim Kraska": ["EECS"],
    "Barbara Liskov": ["EECS"],
    "Kuikui Liu": ["EECS", "LIDS"],
    "Tomás Lozano-Pérez": ["EECS"],
    "Nancy Lynch": ["EECS"],
    "Samuel Madden": ["EECS"],
    "Aleksander Mądry": ["EECS"],
    "Wojciech Matusik": ["EECS", "MechE"],
    "Muriel Médard": ["EECS"],
    "Silvio Micali": ["EECS"],
    "Ankur Moitra": ["EECS", "Math"],
    "Robert Morris": ["EECS"],
    "Stefanie Mueller": ["EECS", "MechE"],
    "Sendhil Mullainathan": ["EECS", "Economics", "LIDS"],
    "Farnaz Niroui": ["EECS"],
    "William D. Oliver": ["EECS", "Physics"],
    "Asu Ozdaglar": ["EECS", "LIDS", "IDSS"],
    "Asuman Ozdaglar": ["EECS", "LIDS", "IDSS"],
    "Mina Konakovic Lukovic": ["EECS"],
    "Jing Kong": ["EECS"],
    "Paul Liang": ["EECS", "LIDS", "IDSS"],
    "Andrew Lo": ["EECS", "LIDS", "IDSS"],
    "Alexander Rives": ["EECS", "LIDS"],
    "Devavrat Shah": ["EECS", "LIDS", "IDSS"],
    "Sertac Karaman": ["EECS", "LIDS", "IDSS"],
    "Yury Polyanskiy": ["EECS", "LIDS", "IDSS"],
    "Caroline Uhler": ["EECS", "LIDS", "IDSS"],
    "Gregory Wornell": ["EECS", "IDSS"],
    "Moe Win": ["EECS", "LIDS", "IDSS"],

    # ── EAPS (Course 12) ──
    "Andrew Babbin": ["EAPS"],
    "Kristin Bergmann": ["EAPS"],
    "Richard P Binzel": ["EAPS"],
    "Richard Binzel": ["EAPS"],
    "Tanja Bosak": ["EAPS"],
    "Edward A Boyle": ["EAPS"],
    "Rogier Braakman": ["EAPS"],
    "Kerri Cahoy": ["EAPS"],
    "Camilla Cattania": ["EAPS"],
    "Timothy Cronin": ["EAPS"],
    "Julien de Wit": ["EAPS"],
    "Francesca E DeMeo": ["EAPS"],
    "Francesca DeMeo": ["EAPS"],
    "Arlene Fiore": ["EAPS"],
    "Glenn Richard Flierl": ["EAPS"],
    "Mick Follows": ["EAPS"],
    "Michael Follows": ["EAPS", "CEE"],
    "Gregory P. Fournier": ["EAPS"],
    "William Frank": ["EAPS"],
    "Bradford H Hager": ["EAPS"],
    "Thomas A Herring": ["EAPS"],
    "Oliver E Jagoutz": ["EAPS"],
    "Wanying Kang": ["EAPS"],
    "Richard Lindzen": ["EAPS"],
    "David McGee": ["EAPS"],
    "Brent Minchew": ["EAPS"],
    "Paul Ambrose O'Gorman": ["EAPS"],
    "Shuhei Ono": ["EAPS"],
    "Matej Pec": ["EAPS"],
    "Taylor Perron": ["EAPS"],
    "Raymond Pierrehumbert": ["EAPS"],
    "Ronald G Prinn": ["EAPS"],
    "Benjamin Rackham": ["EAPS"],
    "Jahandar Ramezani": ["EAPS"],
    "Daniel H Rothman": ["EAPS"],
    "Leigh H Royden": ["EAPS"],
    "Adam Schlosser": ["EAPS"],
    "Sara Seager": ["EAPS", "Physics"],
    "Noelle Eckley Selin": ["EAPS", "IDSS"],
    "Noelle Selin": ["EAPS", "IDSS"],
    "Roger Everett Summons": ["EAPS"],
    "Talia Tamarin-Brodsky": ["EAPS"],
    "Richard Teague": ["EAPS"],
    "Robert D van der Hilst": ["EAPS"],
    "Maria Zuber": ["EAPS"],

    # ── Economics (Course 14) ──
    "Alberto Abadie": ["Economics", "IDSS"],
    "Daron Acemoglu": ["Economics", "LIDS", "IDSS"],
    "Nikhil Agarwal": ["Economics"],
    "Isaiah Andrews": ["Economics"],
    "Josh Angrist": ["Economics"],
    "David Atkin": ["Economics"],
    "David H. Autor": ["Economics"],
    "David Autor": ["Economics"],
    "Ian Ball": ["Economics"],
    "Abhijit Banerjee": ["Economics"],
    "Ricardo Caballero": ["Economics"],
    "Victor Chernozhukov": ["Economics", "IDSS"],
    "Arnaud Costinot": ["Economics"],
    "Peter Diamond": ["Economics"],
    "Dave Donaldson": ["Economics"],
    "Esther Duflo": ["Economics", "IDSS"],
    "Glenn Ellison": ["Economics"],
    "Sara Fisher Ellison": ["Economics"],
    "Amy Finkelstein": ["Economics"],
    "Drew Fudenberg": ["Economics"],
    "Robert Gibbons": ["Economics"],
    "Jonathan Gruber": ["Economics"],
    "Jerry Hausman": ["Economics"],
    "Nathaniel Hendren": ["Economics"],
    "Bengt Holmström": ["Economics"],
    "Anna Mikusheva": ["Economics"],
    "Stephen Morris": ["Economics"],
    "Jacob Moscona": ["Economics"],
    "Whitney Newey": ["Economics", "IDSS"],
    "Benjamin Olken": ["Economics"],
    "Parag Pathak": ["Economics"],
    "James Poterba": ["Economics"],
    "Drazen Prelec": ["Economics", "BCS"],
    "Ashesh Rambachan": ["Economics", "LIDS"],
    "Nancy L. Rose": ["Economics"],
    "Nina Roussille": ["Economics"],
    "Tobias Salz": ["Economics"],
    "Frank Schilbach": ["Economics"],
    "Richard Schmalensee": ["Economics"],
    "Robert M. Townsend": ["Economics"],
    "Iván Werning": ["Economics"],
    "Michael Whinston": ["Economics"],
    "Christian Wolf": ["Economics"],
    "Alexander Wolitzky": ["Economics"],
    "Muhamet Yildiz": ["Economics"],

    # ── Biological Engineering (Course 20) ──
    "Eric Alm": ["BioE", "CEE"],
    "Mark Bathe": ["BioE", "MechE"],
    "Angela Belcher": ["BioE", "DMSE", "Koch Institute"],
    "Michael Birnbaum": ["BioE", "Koch Institute"],
    "Paul Blainey": ["BioE", "Koch Institute"],
    "Ed Boyden": ["BioE", "BCS", "McGovern", "Koch Institute"],
    "Edward Boyden": ["BioE", "BCS", "McGovern", "Koch Institute"],
    "Bryan Bryson": ["BioE"],
    "Cullen Buie": ["BioE", "MechE"],
    "James J. Collins": ["BioE"],
    "Peter Dedon": ["BioE"],
    "Domitilla Del Vecchio": ["BioE", "MechE"],
    "Bevin P. Engelward": ["BioE"],
    "Ernest Fraenkel": ["BioE"],
    "Linda G. Griffith": ["BioE", "MechE", "Koch Institute"],
    "Linda Griffith": ["BioE", "MechE", "Koch Institute"],
    "Anders Sejr Hansen": ["BioE", "Koch Institute"],
    "Anders Hansen": ["BioE", "Koch Institute"],
    "Alan Jasanoff": ["BioE", "BCS", "McGovern"],
    "Roger D. Kamm": ["BioE", "MechE"],
    "Roger Kamm": ["BioE", "MechE"],
    "Angela Koehler": ["BioE", "Koch Institute"],
    "Robert Langer": ["BioE", "MechE", "Koch Institute"],
    "Scott Manalis": ["BioE", "MechE", "Koch Institute"],
    "Jacquin C. Niles": ["BioE"],
    "Katharina Ribbeck": ["BioE"],
    "Ram Sasisekharan": ["BioE", "Koch Institute"],
    "Peter So": ["BioE", "MechE"],
    "Jessica Stark": ["BioE", "Koch Institute"],
    "Bruce Tidor": ["BioE"],
    "Christopher A. Voigt": ["BioE"],
    "Ron Weiss": ["BioE", "Koch Institute"],
    "Forest White": ["BioE", "Koch Institute"],
    "K. Dane Wittrup": ["BioE", "Koch Institute"],
    "Feng Zhang": ["BioE", "McGovern"],

    # ── Chemical Engineering (Course 10) ──
    # (cheme.mit.edu didn't render names; adding known faculty)

    # ── Mechanical Engineering (Course 2) ──
    "Rohan Abeyaratne": ["MechE"],
    "Faez Ahmed": ["MechE", "IDSS"],
    "Triantaphyllos R Akylas": ["MechE"],
    "Anuradha M Annaswamy": ["MechE", "LIDS"],
    "Anuradha Annaswamy": ["MechE", "LIDS"],
    "Brian Anthony": ["MechE"],
    "Harry Asada": ["MechE"],
    "Navid Azizan": ["MechE", "LIDS", "IDSS"],
    "George Barbastathis": ["MechE"],
    "Klaus-Jürgen Bathe": ["MechE"],
    "Kaitlyn Becker": ["MechE"],
    "Irmgard Bischofberger": ["MechE"],
    "Lydia Bourouiba": ["MechE", "CEE"],
    "Markus Buehler": ["MechE", "CEE"],
    "Tonio Buonassisi": ["MechE"],
    "Gang Chen": ["MechE"],
    "Tal Cohen": ["MechE", "CEE"],
    "Martin Culpepper": ["MechE"],
    "Sili Deng": ["MechE"],
    "Daniel Frey": ["MechE"],
    "Betar Gallant": ["MechE"],
    "Ahmed F Ghoniem": ["MechE"],
    "Ming Guo": ["MechE"],
    "Nicolas Hadjiconstantinou": ["MechE"],
    "A. John Hart": ["MechE"],
    "Asegun Henry": ["MechE"],
    "Neville Hogan": ["MechE", "BCS"],
    "Ian Hunter": ["MechE"],
    "Rohit N Karnik": ["MechE"],
    "Jeehwan Kim": ["MechE"],
    "Sangbae Kim": ["MechE"],
    "Mathias Kolle": ["MechE"],
    "John H Lienhard": ["MechE"],
    "John Lienhard": ["MechE"],
    "John Leonard": ["MechE"],
    "Pierre Lermusiaux": ["MechE"],
    "Seth Lloyd": ["MechE"],
    "Gareth H McKinley": ["MechE"],
    "Gareth McKinley": ["MechE"],
    "Thomas Peacock": ["MechE"],
    "Carlos Portela": ["MechE"],
    "Ritu Raman": ["MechE"],
    "Ellen Roche": ["MechE"],
    "Themistoklis Sapsis": ["MechE", "IDSS"],
    "Sanjay E Sarma": ["MechE"],
    "Sanjay Sarma": ["MechE"],
    "Alexander H Slocum": ["MechE"],
    "Jean-Jacques E Slotine": ["MechE", "BCS", "IDSS"],
    "Jean-Jacques Slotine": ["MechE", "BCS", "IDSS"],
    "Russ Tedrake": ["MechE", "EECS"],
    "Giovanni Traverso": ["MechE", "Koch Institute"],
    "Kripa Varanasi": ["MechE"],
    "Evelyn N. Wang": ["MechE"],
    "Evelyn Wang": ["MechE"],
    "Sherrie Wang": ["MechE", "LIDS", "IDSS"],
    "Brian Wardle": ["MechE"],
    "Xuanhe Zhao": ["MechE", "CEE"],

    # ── Civil & Environmental Engineering (Course 1) ──
    "Saurabh Amin": ["CEE", "LIDS", "IDSS"],
    "Moshe E. Ben-Akiva": ["CEE"],
    "Josephine V. Carstensen": ["CEE"],
    "Otto Cordero": ["CEE"],
    "David L. Des Marais": ["CEE"],
    "Elfatih Eltahir": ["CEE"],
    "Dara Entekhabi": ["CEE"],
    "Charles F. Harvey": ["CEE"],
    "Michael F. Howland": ["CEE"],
    "Ali Jadbabaie": ["CEE", "LIDS", "IDSS"],
    "Patrick Jaillet": ["CEE", "LIDS", "IDSS"],
    "Ruben Juanes": ["CEE"],
    "Jesse Kroll": ["CEE"],
    "Tami Lieberman": ["CEE"],
    "Benedetto Marelli": ["CEE"],
    "Admir Masic": ["CEE"],
    "Darcy McRose": ["CEE"],
    "Caitlin Mueller": ["CEE"],
    "Heidi Nepf": ["CEE"],
    "Desirée Plata": ["CEE"],
    "Serguei Saavedra": ["CEE"],
    "Yossi Sheffi": ["CEE", "IDSS"],
    "David Simchi-Levi": ["CEE", "LIDS", "IDSS"],
    "César Terrer": ["CEE"],
    "Franz-Josef Ulm": ["CEE"],
    "Andrew Whittle": ["CEE"],
    "Cathy Wu": ["CEE", "LIDS", "IDSS"],
    "Gioele Zardini": ["CEE", "IDSS"],
    "Jinhua Zhao": ["CEE", "IDSS"],

    # ── Materials Science & Engineering (Course 3 / DMSE) ──
    "Iwnetim Abate": ["DMSE"],
    "Alfredo Alexander-Katz": ["DMSE"],
    "Antoine Allanore": ["DMSE"],
    "Polina Anikeeva": ["DMSE", "BCS", "McGovern"],
    "Geoffrey S.D. Beach": ["DMSE"],
    "Geoffrey Beach": ["DMSE"],
    "W. Craig Carter": ["DMSE"],
    "Joseph Casamento": ["DMSE"],
    "Yet-Ming Chiang": ["DMSE"],
    "Michael J. Cima": ["DMSE", "Koch Institute"],
    "Yoel Fink": ["DMSE"],
    "Eugene A. Fitzgerald": ["DMSE"],
    "Rodrigo Freitas": ["DMSE"],
    "Lorna J. Gibson": ["DMSE"],
    "Rafael Gómez-Bombarelli": ["DMSE"],
    "Jeffrey Grossman": ["DMSE"],

    # ── Brain & Cognitive Sciences (Course 9) ──
    "Edward H Adelson": ["BCS"],
    "Mark Bear": ["BCS"],
    "Emery N Brown": ["BCS", "IDSS"],
    "Emery Brown": ["BCS", "IDSS"],
    "Gloria Choi": ["BCS"],
    "Kwanghun Chung": ["BCS"],
    "Robert Desimone": ["BCS", "McGovern"],
    "James DiCarlo": ["BCS", "McGovern"],
    "Sven Dorkenwald": ["BCS", "McGovern"],
    "Linlin Fan": ["BCS"],
    "Evelina Fedorenko": ["BCS", "McGovern"],
    "Michale S Fee": ["BCS", "McGovern"],
    "Michale Fee": ["BCS", "McGovern"],
    "Guoping Feng": ["BCS", "McGovern"],
    "Ila Fiete": ["BCS", "McGovern"],
    "Steven Flavell": ["BCS"],
    "John D. E. Gabrieli": ["BCS", "McGovern"],
    "John Gabrieli": ["BCS", "McGovern"],
    "Edward A Gibson": ["BCS"],
    "Ann M. Graybiel": ["BCS", "McGovern"],
    "Ann Graybiel": ["BCS", "McGovern"],
    "Mark Thomas Harnett": ["BCS", "McGovern"],
    "Mark Harnett": ["BCS", "McGovern"],
    "Myriam Heiman": ["BCS"],
    "Mehrdad Jazayeri": ["BCS", "McGovern"],
    "Nancy Kanwisher": ["BCS", "McGovern"],
    "Roger Levy": ["BCS"],
    "Josh McDermott": ["BCS", "McGovern"],
    "Earl K Miller": ["BCS"],
    "Tomaso A Poggio": ["BCS", "McGovern"],
    "Tomaso Poggio": ["BCS", "McGovern"],
    "Rebecca R Saxe": ["BCS", "McGovern"],
    "Rebecca Saxe": ["BCS", "McGovern"],
    "Laura E Schulz": ["BCS"],
    "Laura Schulz": ["BCS"],
    "Nidhi Seethapathi": ["BCS", "McGovern"],
    "Pawan Sinha": ["BCS"],
    "Mriganka Sur": ["BCS"],
    "Joshua B Tenenbaum": ["BCS"],
    "Joshua Tenenbaum": ["BCS"],
    "Li-Huei Tsai": ["BCS"],
    "Fan Wang": ["BCS", "McGovern"],

    # ── Nuclear Science & Engineering (Course 22) ──
    "Emilio Baglietto": ["NSE"],
    "Matteo Bucci": ["NSE"],
    "Jacopo Buongiorno": ["NSE", "MechE"],
    "Areg Danagoulian": ["NSE"],
    "Benoit Forget": ["NSE"],
    "Zachary Hartwig": ["NSE"],
    "Sophia Henneberg": ["NSE"],
    "Ericmoore Jossou": ["NSE", "EECS"],
    "R. Scott Kemp": ["NSE"],
    "Richard K. Lester": ["NSE"],
    "Ju Li": ["NSE", "DMSE"],
    "Mingda Li": ["NSE"],
    "Ethan Peterson": ["NSE"],
    "Koroush Shirvan": ["NSE"],
    "Michael Short": ["NSE"],
    "Curtis Smith": ["NSE"],
    "Haruko Murakami Wainwright": ["NSE", "CEE"],
    "Anne White": ["NSE"],
    "Dennis G. Whyte": ["NSE"],
    "Bilge Yildiz": ["NSE"],

    # ── McGovern Institute ──
    "Hugh Herr": ["McGovern", "MechE"],
    "Ian Wickersham": ["McGovern"],
    "Satrajit Ghosh": ["McGovern"],

    # ── Koch Institute (additional not already listed) ──
    "Daniel Anderson": ["Koch Institute"],
    "Paula Hammond": ["Koch Institute", "ChemE"],
    "Susan Hockfield": ["Koch Institute", "BCS"],
    "J. Christopher Love": ["Koch Institute"],
    "Phillip Sharp": ["Koch Institute"],
    "Brandon DeKosky": ["Koch Institute"],
    "Patrick Doyle": ["Koch Institute", "ChemE"],
    "Katie Galloway": ["Koch Institute"],

    # ── AeroAstro (Course 16, partial) ──
    "Hamsa Balakrishnan": ["AeroAstro", "LIDS", "IDSS"],

    # ── LIDS / IDSS additional ──
    "Luca Carlone": ["LIDS", "IDSS"],
    "Chuchu Fan": ["LIDS"],
    "Eytan Modiano": ["LIDS", "IDSS"],
    "Kalyan Veeramachaneni": ["LIDS"],
    "Ashia Wilson": ["LIDS"],
    "Benjamin Lindquist": ["LIDS"],
    "Bailey Flanigan": ["LIDS"],
    "Jonathan How": ["LIDS"],
    "David Gamarnik": ["IDSS"],
    "Dean Eckles": ["IDSS"],
    "Rahul Mazumder": ["IDSS"],
    "David Sontag": ["EECS", "IDSS"],
    "John Tsitsiklis": ["EECS", "IDSS"],
    "Jessika Trancik": ["IDSS"],
    "Daniel Varon": ["IDSS", "EAPS"],
}


def get_verified_names():
    """Return a set of normalized names for matching."""
    import re
    names = set()
    for name in VERIFIED_FACULTY:
        # Normalize: lowercase, strip accents roughly, remove middle initials
        n = name.lower().strip()
        # Remove common suffixes
        n = re.sub(r",?\s*(jr\.?|sr\.?|iii?|iv)$", "", n, flags=re.I)
        # Remove middle initials like "A." or "H."
        n = re.sub(r"\s+[a-z]\.?\s+", " ", n)
        # Remove periods
        n = n.replace(".", "")
        # Normalize whitespace
        n = " ".join(n.split())
        names.add(n)
    return names


def get_departments_for_name(name):
    """Look up departments for a faculty name (fuzzy match)."""
    import re
    # Try exact match first
    if name in VERIFIED_FACULTY:
        return VERIFIED_FACULTY[name]

    # Try normalized match
    norm = name.lower().strip()
    norm = re.sub(r",?\s*(jr\.?|sr\.?|iii?|iv)$", "", norm, flags=re.I)
    norm = re.sub(r"\s+[a-z]\.?\s+", " ", norm)
    norm = norm.replace(".", "")
    norm = " ".join(norm.split())

    for faculty_name, depts in VERIFIED_FACULTY.items():
        fn = faculty_name.lower().strip()
        fn = re.sub(r",?\s*(jr\.?|sr\.?|iii?|iv)$", "", fn, flags=re.I)
        fn = re.sub(r"\s+[a-z]\.?\s+", " ", fn)
        fn = fn.replace(".", "")
        fn = " ".join(fn.split())

        if fn == norm:
            return depts

        # Match on last name + first name initial
        norm_parts = norm.split()
        fn_parts = fn.split()
        if norm_parts and fn_parts:
            if norm_parts[-1] == fn_parts[-1] and norm_parts[0][0] == fn_parts[0][0]:
                # Additional check: if first names are substantially different, skip
                if len(norm_parts[0]) > 1 and len(fn_parts[0]) > 1:
                    from difflib import SequenceMatcher
                    if SequenceMatcher(None, norm_parts[0], fn_parts[0]).ratio() < 0.6:
                        continue
                return depts

    return None
